export interface ILuojigouCourse {
  id: string
  name: string
  imgCover: string
  imgCoverMini: null
  createTime: string
  updateTime: string
  price: number
  markingPrice: number
  categoryId: string
  courseCount: number
  aiCourseSpuId: string
  suitAge: string
  wxNumber: null
  wxQrCode: null
  wxName: null
  wxHeadImg: null
  description: string
  mediaType: number
  simpleDescription: string
  sort: number
  showChapter: number
  courseType: number
  subCategoryId: string
  activityTag: null
  courseTags: null
  paidCount: null
  latestLearnedRecordId: null
  latestLearnedRecord: null
  abilityList: null
  commentCount: null
  shareCount: null
  collectCount: null
  isCollect: null
  hasPaid: number
  isComment: null
  isShare: null
  imgCoverWidth: null
  imgCoverHeight: null
  shareUrl: null
  shareUrlQRCode: null
  groupBuyActivity: null
  groupBuyActivityId: null
  groupBuyActivityUrl: null
  totalLearnUser: null
  userCount: number
  categoryName: string
  avatars: string[]
}
